project:
  type: website
theme: lux
execute:
  freeze: auto
date: last-modified  
format:
  html: 
    toc: true


website:
  title: "hmt"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "The Archive"
        file: archive/index.qmd 
      - text: "Digital images"
        file: images/index.qmd   
      - text: "News"
        file: news.qmd                     
    right:   
      - icon: person-circle
        menu:
          - text: "About me"
            href: https://neelsmith.quarto.pub
          - text: "More of my digital scholarship"
            href: https://neelsmith.quarto.pub/digschol/
        aria-label: "More of my work"  

  sidebar:
    - title: "Home"
      contents:
        - index.qmd               
    - title: "The Archive"
      contents:
        - archive/index.qmd
        - archive/orientation/index.qmd